COUNTRIES = (
    ('AF', 'Afghanistan',),
    ('AX', 'Aland Islands',),
    ('AL', 'Albania',),
    ('DZ', 'Algeria',),
    ('AS', 'American Samoa',),
    ('AD', 'Andorra',),
    ('AO', 'Angola',),
    ('AI', 'Anguilla',),
    ('AQ', 'Antarctica',),
    ('AG', 'Antigua and Barbuda',),
    ('AR', 'Argentina',),
    ('AM', 'Armenia',),
    ('AW', 'Aruba',),
    ('AU', 'Australia',),
    ('AT', 'Austria',),
    ('AZ', 'Azerbaijan',),
    ('BS', 'Bahamas',),
    ('BH', 'Bahrain',),
    ('BD', 'Bangladesh',),
    ('BB', 'Barbados',),
    ('BY', 'Belarus',),
    ('BE', 'Belgium',),
    ('BZ', 'Belize',),
    ('BJ', 'Benin',),
    ('BM', 'Bermuda',),
    ('BT', 'Bhutan',),
    ('BO', 'Bolivia, Plurinational State of',),
    ('BQ', 'Bonaire, Sint Eustatius and Saba',),
    ('BA', 'Bosnia and Herzegovina',),
    ('BW', 'Botswana',),
    ('BV', 'Bouvet Island',),
    ('BR', 'Brazil',),
    ('IO', 'British Indian Ocean Territory',),
    ('BN', 'Brunei Darussalam',),
    ('BG', 'Bulgaria',),
    ('BF', 'Burkina Faso',),
    ('BI', 'Burundi',),
    ('KH', 'Cambodia',),
    ('CM', 'Cameroon',),
    ('CA', 'Canada',),
    ('CV', 'Cape Verde',),
    ('KY', 'Cayman Islands',),
    ('CF', 'Central African Republic',),
    ('TD', 'Chad',),
    ('CL', 'Chile',),
    ('CN', 'China',),
    ('CX', 'Christmas Island',),
    ('CC', 'Cocos (Keeling) Islands',),
    ('CO', 'Colombia',),
    ('KM', 'Comoros',),
    ('CG', 'Congo',),
    ('CD', 'Congo, the Democratic Republic of the',),
    ('CK', 'Cook Islands',),
    ('CR', 'Costa Rica',),
    ('CI', "Cote d'Ivoire",),
    ('HR', 'Croatia',),
    ('CU', 'Cuba',),
    ('CW', 'Curacao',),
    ('CY', 'Cyprus',),
    ('CZ', 'Czech Republic',),
    ('DK', 'Denmark',),
    ('DJ', 'Djibouti',),
    ('DM', 'Dominica',),
    ('DO', 'Dominican Republic',),
    ('EC', 'Ecuador',),
    ('EG', 'Egypt',),
    ('SV', 'El Salvador',),
    ('GQ', 'Equatorial Guinea',),
    ('ER', 'Eritrea',),
    ('EE', 'Estonia',),
    ('ET', 'Ethiopia',),
    ('FK', 'Falkland Islands (Malvinas)',),
    ('FO', 'Faroe Islands',),
    ('FJ', 'Fiji',),
    ('FI', 'Finland',),
    ('FR', 'France',),
    ('GF', 'French Guiana',),
    ('PF', 'French Polynesia',),
    ('TF', 'French Southern Territories',),
    ('GA', 'Gabon',),
    ('GM', 'Gambia',),
    ('GE', 'Georgia',),
    ('DE', 'Germany',),
    ('GH', 'Ghana',),
    ('GI', 'Gibraltar',),
    ('GR', 'Greece',),
    ('GL', 'Greenland',),
    ('GD', 'Grenada',),
    ('GP', 'Guadeloupe',),
    ('GU', 'Guam',),
    ('GT', 'Guatemala',),
    ('GG', 'Guernsey',),
    ('GN', 'Guinea',),
    ('GW', 'Guinea-Bissau',),
    ('GY', 'Guyana',),
    ('HT', 'Haiti',),
    ('HM', 'Heard Island and McDonald Islands',),
    ('VA', 'Holy See (Vatican City State)',),
    ('HN', 'Honduras',),
    ('HK', 'Hong Kong',),
    ('HU', 'Hungary',),
    ('IS', 'Iceland',),
    ('IN', 'India',),
    ('ID', 'Indonesia',),
    ('IR', 'Iran, Islamic Republic of',),
    ('IQ', 'Iraq',),
    ('IE', 'Ireland',),
    ('IM', 'Isle of Man',),
    ('IL', 'Israel',),
    ('IT', 'Italy',),
    ('JM', 'Jamaica',),
    ('JP', 'Japan',),
    ('JE', 'Jersey',),
    ('JO', 'Jordan',),
    ('KZ', 'Kazakhstan',),
    ('KE', 'Kenya',),
    ('KI', 'Kiribati',),
    ('KP', "Korea, Democratic People's Republic of",),
    ('KR', 'Korea, Republic of',),
    ('KW', 'Kuwait',),
    ('KG', 'Kyrgyzstan',),
    ('LA', "Lao People's Democratic Republic",),
    ('LV', 'Latvia',),
    ('LB', 'Lebanon',),
    ('LS', 'Lesotho',),
    ('LR', 'Liberia',),
    ('LY', 'Libya',),
    ('LI', 'Liechtenstein',),
    ('LT', 'Lithuania',),
    ('LU', 'Luxembourg',),
    ('MO', 'Macao',),
    ('MK', 'Macedonia, the former Yugoslav Republic of',),
    ('MG', 'Madagascar',),
    ('MW', 'Malawi',),
    ('MY', 'Malaysia',),
    ('MV', 'Maldives',),
    ('ML', 'Mali',),
    ('MT', 'Malta',),
    ('MH', 'Marshall Islands',),
    ('MQ', 'Martinique',),
    ('MR', 'Mauritania',),
    ('MU', 'Mauritius',),
    ('YT', 'Mayotte',),
    ('MX', 'Mexico',),
    ('FM', 'Micronesia, Federated States of',),
    ('MD', 'Moldova, Republic of',),
    ('MC', 'Monaco',),
    ('MN', 'Mongolia',),
    ('ME', 'Montenegro',),
    ('MS', 'Montserrat',),
    ('MA', 'Morocco',),
    ('MZ', 'Mozambique',),
    ('MM', 'Myanmar',),
    ('NA', 'Namibia',),
    ('NR', 'Nauru',),
    ('NP', 'Nepal',),
    ('NL', 'Netherlands',),
    ('NC', 'New Caledonia',),
    ('NZ', 'New Zealand',),
    ('NI', 'Nicaragua',),
    ('NE', 'Niger',),
    ('NG', 'Nigeria',),
    ('NU', 'Niue',),
    ('NF', 'Norfolk Island',),
    ('MP', 'Northern Mariana Islands',),
    ('NO', 'Norway',),
    ('OM', 'Oman',),
    ('PK', 'Pakistan',),
    ('PW', 'Palau',),
    ('PS', 'Palestine, State of',),
    ('PA', 'Panama',),
    ('PG', 'Papua New Guinea',),
    ('PY', 'Paraguay',),
    ('PE', 'Peru',),
    ('PH', 'Philippines',),
    ('PN', 'Pitcairn',),
    ('PL', 'Poland',),
    ('PT', 'Portugal',),
    ('PR', 'Puerto Rico',),
    ('QA', 'Qatar',),
    ('RE', 'Reunion',),
    ('RO', 'Romania',),
    ('RU', 'Russian Federation',),
    ('RW', 'Rwanda',),
    ('BL', 'Saint Barthelemy',),
    ('SH', 'Saint Helena, Ascension and Tristan da Cunha',),
    ('KN', 'Saint Kitts and Nevis',),
    ('LC', 'Saint Lucia',),
    ('MF', 'Saint Martin (French part)',),
    ('PM', 'Saint Pierre and Miquelon',),
    ('VC', 'Saint Vincent and the Grenadines',),
    ('WS', 'Samoa',),
    ('SM', 'San Marino',),
    ('ST', 'Sao Tome and Principe',),
    ('SA', 'Saudi Arabia',),
    ('SN', 'Senegal',),
    ('RS', 'Serbia',),
    ('SC', 'Seychelles',),
    ('SL', 'Sierra Leone',),
    ('SG', 'Singapore',),
    ('SX', 'Sint Maarten (Dutch part)',),
    ('SK', 'Slovakia',),
    ('SI', 'Slovenia',),
    ('SB', 'Solomon Islands',),
    ('SO', 'Somalia',),
    ('ZA', 'South Africa',),
    ('GS', 'South Georgia and the South Sandwich Islands',),
    ('SS', 'South Sudan',),
    ('ES', 'Spain',),
    ('LK', 'Sri Lanka',),
    ('SD', 'Sudan',),
    ('SR', 'Suriname',),
    ('SJ', 'Svalbard and Jan Mayen',),
    ('SZ', 'Swaziland',),
    ('SE', 'Sweden',),
    ('CH', 'Switzerland',),
    ('SY', 'Syrian Arab Republic',),
    ('TW', 'Taiwan, Province of China',),
    ('TJ', 'Tajikistan',),
    ('TZ', 'Tanzania, United Republic of',),
    ('TH', 'Thailand',),
    ('TL', 'Timor-Leste',),
    ('TG', 'Togo',),
    ('TK', 'Tokelau',),
    ('TO', 'Tonga',),
    ('TT', 'Trinidad and Tobago',),
    ('TN', 'Tunisia',),
    ('TR', 'Turkey',),
    ('TM', 'Turkmenistan',),
    ('TC', 'Turks and Caicos Islands',),
    ('TV', 'Tuvalu',),
    ('UG', 'Uganda',),
    ('UA', 'Ukraine',),
    ('AE', 'United Arab Emirates',),
    ('GB', 'United Kingdom',),
    ('US', 'United States',),
    ('UM', 'United States Minor Outlying Islands',),
    ('UY', 'Uruguay',),
    ('UZ', 'Uzbekistan',),
    ('VU', 'Vanuatu',),
    ('VE', 'Venezuela, Bolivarian Republic of',),
    ('VN', 'Viet Nam',),
    ('VG', 'Virgin Islands, British',),
    ('VI', 'Virgin Islands, U.S.',),
    ('WF', 'Wallis and Futuna',),
    ('EH', 'Western Sahara',),
    ('YE', 'Yemen',),
    ('ZM', 'Zambia',),
    ('ZW', 'Zimbabwe',),
)

COMPANIES = [ "3 Round Stones, Inc.","48 Factoring Inc.","5PSolutions","Abt Associates","Accela","Accenture","AccuWeather","Acxiom","Adaptive","Adobe Digital Government","Aidin","Alarm.com","Allianz","Allied Van Lines","AllState Insurance Group","Alltuition","Altova","Amazon Web Services","American Red Ball Movers","Amida Technology Solutions","Analytica","Apextech LLC","Appallicious","Aquicore","Archimedes Inc.","AreaVibes Inc." ,"Arpin Van Lines","Arrive Labs","ASC Partners","Asset4","Atlas Van Lines","AtSite","Aunt Bertha, Inc.","Aureus Sciences (*Now part of Elsevier)","AutoGrid Systems","Avalara","Avvo","Ayasdi","Azavea","BaleFire Global","Barchart","Be Informed","Bekins","Berkery Noyes MandASoft","Berkshire Hathaway","BetterLesson","BillGuard","Bing","Biovia","BizVizz","BlackRock","Bloomberg","Booz Allen Hamilton","Boston Consulting Group","Boundless","Bridgewater","Brightscope","BuildFax","Buildingeye","BuildZoom","Business and Legal Resources","Business Monitor International","Calcbench, Inc.","Cambridge Information Group","Cambridge Semantics","CAN Capital","Canon","Capital Cube","Cappex","Captricity","CareSet Systems","Careset.com","CARFAX","Caspio","Castle Biosciences","CB Insights","Ceiba Solutions","Center for Responsive Politics","Cerner","Certara","CGI","Charles River Associates","Charles Schwab Corp.","Chemical Abstracts Service","Child Care Desk","Chubb","Citigroup","CityScan","CitySourced","Civic Impulse LLC","Civic Insight","Civinomics","Civis Analytics","Clean Power Finance","ClearHealthCosts","ClearStory Data","Climate Corporation","CliniCast","Cloudmade","Cloudspyre","Code for America","Code-N","Collective IP","College Abacus, an ECMC initiative","College Board","Compared Care","Compendia Bioscience Life Technologies","Compliance and Risks","Computer Packages Inc","CONNECT-DOT LLC.","ConnectEDU","Connotate","Construction Monitor LLC","Consumer Reports","CoolClimate","Copyright Clearance Center","CoreLogic","CostQuest","Credit Karma","Credit Sesame","CrowdANALYTIX","Dabo Health","DataLogix","DataMade","DataMarket","Datamyne","DataWeave","Deloitte","DemystData","Department of Better Technology","Development Seed","Docket Alarm, Inc.","Dow Jones & Co.","Dun & Bradstreet","Earth Networks","EarthObserver App","Earthquake Alert!","Eat Shop Sleep","Ecodesk","eInstitutional","Embark","EMC","Energy Points, Inc.","Energy Solutions Forum","Enervee Corporation","Enigma.io","Ensco","Environmental Data Resources","Epsilon","Equal Pay for Women","Equifax","Equilar","Ernst & Young LLP","eScholar LLC.","Esri","Estately","Everyday Health","Evidera","Experian","Expert Health Data Programming, Inc.","Exversion","Ez-XBRL","Factset","Factual","Farmers","FarmLogs","Fastcase","Fidelity Investments","FindTheBest.com","First Fuel Software","FirstPoint, Inc.","Fitch","FlightAware","FlightStats","FlightView","Food+Tech Connect","Forrester Research","Foursquare","Fujitsu","Funding Circle","FutureAdvisor","Fuzion Apps, Inc.","Gallup","Galorath Incorporated","Garmin","Genability","GenoSpace","Geofeedia","Geolytics","Geoscape","GetRaised","GitHub","Glassy Media","Golden Helix","GoodGuide","Google Maps","Google Public Data Explorer","Government Transaction Services","Govini","GovTribe","Govzilla, Inc.","gRadiant Research LLC","Graebel Van Lines","Graematter, Inc.","Granicus","GreatSchools","GuideStar","H3 Biomedicine","Harris Corporation","HDScores, Inc","Headlight","Healthgrades","Healthline","HealthMap","HealthPocket, Inc.","HelloWallet","HERE","Honest Buildings","HopStop","Housefax","How's My Offer?","IBM","ideas42","iFactor Consulting","IFI CLAIMS Patent Services","iMedicare","Impact Forecasting (Aon)","Impaq International","Import.io","IMS Health","InCadence","indoo.rs","InfoCommerce Group","Informatica","InnoCentive","Innography","Innovest Systems","Inovalon","Inrix Traffic","Intelius","Intermap Technologies","Investormill","Iodine","IPHIX","iRecycle","iTriage","IVES Group Inc","IW Financial","JJ Keller","J.P. Morgan Chase","Junar, Inc.","Junyo","Jurispect","Kaiser Permanante","karmadata","Keychain Logistics Corp.","KidAdmit, Inc.","Kimono Labs","KLD Research","Knoema","Knowledge Agency","KPMG","Kroll Bond Ratings Agency","Kyruus","Lawdragon","Legal Science Partners","(Leg)Cyte","LegiNation, Inc.","LegiStorm","Lenddo","Lending Club","Level One Technologies","LexisNexis","Liberty Mutual Insurance Cos.","Lilly Open Innovation Drug Discovery","Liquid Robotics","Locavore","LOGIXDATA, LLC","LoopNet","Loqate, Inc.","LoseIt.com","LOVELAND Technologies","Lucid","Lumesis, Inc.","Mango Transit","Mapbox","Maponics","MapQuest","Marinexplore, Inc.","MarketSense","Marlin & Associates","Marlin Alter and Associates","McGraw Hill Financial","McKinsey","MedWatcher","Mercaris","Merrill Corp.","Merrill Lynch","MetLife","mHealthCoach","MicroBilt Corporation","Microsoft Windows Azure Marketplace","Mint","Moody's","Morgan Stanley","Morningstar, Inc.","Mozio","MuckRock.com","Munetrix","Municode","National Van Lines","Nationwide Mutual Insurance Company","Nautilytics","Navico","NERA Economic Consulting","NerdWallet","New Media Parents","Next Step Living","NextBus","nGAP Incorporated","Nielsen","Noesis","NonprofitMetrics","North American Van Lines","Noveda Technologies","NuCivic","Numedii","Oliver Wyman","OnDeck","OnStar","Ontodia, Inc","Onvia","Open Data Nation","OpenCounter","OpenGov","OpenPlans","OpportunitySpace, Inc.","Optensity","optiGov","OptumInsight","Orlin Research","OSIsoft","OTC Markets","Outline","Oversight Systems","Overture Technologies","Owler","Palantir Technologies","Panjiva","Parsons Brinckerhoff","Patently-O","PatientsLikeMe","Pave","Paxata","PayScale, Inc.","PeerJ","People Power","Persint","Personal Democracy Media","Personal, Inc.","Personalis","Peterson's","PEV4me.com","PIXIA Corp","PlaceILive.com","PlanetEcosystems","PlotWatt","Plus-U","PolicyMap","Politify","Poncho App","POPVOX","Porch","PossibilityU","PowerAdvocate","Practice Fusion","Predilytics","PricewaterhouseCoopers (PWC)","ProgrammableWeb","Progressive Insurance Group","Propeller Health","ProPublica","PublicEngines","PYA Analytics","Qado Energy, Inc.","Quandl","Quertle","Quid","R R Donnelley","RAND Corporation","Rand McNally","Rank and Filed","Ranku","Rapid Cycle Solutions","realtor.com","Recargo","ReciPal","Redfin","RedLaser","Reed Elsevier","REI Systems","Relationship Science","Remi","Retroficiency","Revaluate","Revelstone","Rezolve Group","Rivet Software","Roadify Transit","Robinson + Yu","Russell Investments","Sage Bionetworks","SAP","SAS","Scale Unlimited","Science Exchange","Seabourne","SeeClickFix","SigFig","Simple Energy","SimpleTuition","SlashDB","Smart Utility Systems","SmartAsset","SmartProcure","Smartronix","SnapSense","Social Explorer","Social Health Insights","SocialEffort Inc","Socrata","Solar Census","SolarList","Sophic Systems Alliance","S&P Capital IQ","SpaceCurve","SpeSo Health","Spikes Cavell Analytic Inc","Splunk","Spokeo","SpotCrime","SpotHero.com","Stamen Design","Standard and Poor's","State Farm Insurance","Sterling Infosystems","Stevens Worldwide Van Lines","STILLWATER SUPERCOMPUTING INC","StockSmart","Stormpulse","StreamLink Software","StreetCred Software, Inc","StreetEasy","Suddath","Symcat","Synthicity","T. Rowe Price","Tableau Software","TagniFi","Telenav","Tendril","Teradata","The Advisory Board Company","The Bridgespan Group","The DocGraph Journal","The Govtech Fund","The Schork Report","The Vanguard Group","Think Computer Corporation","Thinknum","Thomson Reuters","TopCoder","TowerData","TransparaGov","TransUnion","TrialTrove","TrialX","Trintech","TrueCar","Trulia","TrustedID","TuvaLabs","Uber","Unigo LLC","United Mayflower","Urban Airship","Urban Mapping, Inc","US Green Data","U.S. News Schools","USAA Group","USSearch","Verdafero","Vimo","VisualDoD, LLC","Vital Axiom | Niinja","VitalChek","Vitals","Vizzuality","Votizen","Walk Score","WaterSmart Software","WattzOn","Way Better Patents","Weather Channel","Weather Decision Technologies","Weather Underground","WebFilings","Webitects","WebMD","Weight Watchers","WeMakeItSafer","Wheaton World Wide Moving","Whitby Group","Wolfram Research","Wolters Kluwer","Workhands","Xatori","Xcential","xDayta","Xignite","Yahoo","Zebu Compliance Solutions","Yelp","YourMapper","Zillow","ZocDoc","Zonability","Zoner","Zurich Insurance (Risk Room)"]
